# Generated by Django 3.1.6 on 2021-07-08 21:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_no_w', models.CharField(default='', max_length=90)),
                ('wcall', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='VerifyOrder',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('sessionid', models.CharField(default='0', max_length=90)),
                ('totalamount', models.CharField(max_length=1000)),
                ('items_json', models.CharField(max_length=5000)),
                ('status', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2021, 7, 9, 3, 7, 13, 462825))),
                ('restaurant', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='setup.venue')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('sessionid', models.CharField(default='0', max_length=90)),
                ('table_no', models.CharField(default='', max_length=90)),
                ('items_json', models.CharField(max_length=5000)),
                ('status', models.IntegerField()),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2021, 7, 9, 3, 7, 13, 461828))),
                ('restaurant', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='setup.venue')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('happiness', models.CharField(max_length=1000)),
                ('feedbacktext', models.TextField()),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2021, 7, 9, 3, 7, 13, 464820))),
                ('restaurant', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='setup.venue')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAuthentication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_no', models.IntegerField()),
                ('hashcode', models.CharField(max_length=1000)),
                ('restaurant', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='setup.venue')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='inactive', max_length=10)),
                ('tablenochoosed', models.IntegerField(default=0)),
                ('customerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialaccount.socialaccount')),
                ('lastrestaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.venue')),
            ],
        ),
        migrations.CreateModel(
            name='ArchiveOrder',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('sessionid', models.CharField(default='0', max_length=90)),
                ('table_no', models.CharField(default='', max_length=90)),
                ('items_json', models.CharField(max_length=5000)),
                ('status', models.IntegerField()),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2021, 7, 9, 3, 7, 13, 463822))),
                ('restaurant', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='setup.venue')),
            ],
        ),
    ]
