# Generated by Django 3.1 on 2020-11-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0002_remove_order_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveOrder',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=5000)),
                ('table_no', models.CharField(default='', max_length=90)),
                ('status', models.IntegerField()),
            ],
        ),
    ]
