# Generated by Django 3.1 on 2020-11-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0003_archiveorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_no_w', models.CharField(default='', max_length=90)),
                ('wcall', models.BooleanField(default=True)),
            ],
        ),
    ]
