# Generated by Django 3.1 on 2020-11-28 16:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0004_waiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiveorder',
            name='field_name',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 28, 21, 57, 19, 784605)),
        ),
        migrations.AddField(
            model_name='order',
            name='field_name',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 28, 21, 57, 19, 783636)),
        ),
    ]
