# Generated by Django 3.1 on 2020-11-30 06:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0005_auto_20201128_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archiveorder',
            name='field_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='field_name',
        ),
        migrations.AddField(
            model_name='archiveorder',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 30, 11, 41, 19, 887643)),
        ),
        migrations.AddField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 30, 11, 41, 19, 886646)),
        ),
    ]
