# Generated by Django 3.1.6 on 2021-06-14 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0006_auto_20210614_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiveorder',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 14, 21, 1, 37, 977756)),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 14, 21, 1, 37, 979764)),
        ),
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 14, 21, 1, 37, 975763)),
        ),
        migrations.AlterField(
            model_name='verifyorder',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 14, 21, 1, 37, 976759)),
        ),
    ]
