# Generated by Django 3.1 on 2020-12-03 16:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0007_auto_20201012_1448'),
        ('customerapp', '0009_auto_20201203_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiveorder',
            name='restaurant',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='setup.venue'),
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='setup.venue'),
        ),
        migrations.AlterField(
            model_name='archiveorder',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 3, 21, 52, 21, 632641)),
        ),
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 3, 21, 52, 21, 632641)),
        ),
    ]
