# Generated by Django 3.1 on 2020-12-09 15:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0009_auto_20201209_1510'),
        ('customerapp', '0012_auto_20201209_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiveorder',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 9, 20, 34, 40, 329525)),
        ),
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 9, 20, 34, 40, 328527)),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('happiness', models.CharField(max_length=1000)),
                ('feedback', models.TextField()),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2020, 12, 9, 20, 34, 40, 330522))),
                ('restaurant', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='setup.venue')),
            ],
        ),
    ]
