# Generated by Django 3.1 on 2020-12-28 09:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0009_auto_20201209_1510'),
        ('customerapp', '0017_auto_20201212_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiveorder',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 28, 15, 12, 17, 754691)),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 28, 15, 12, 17, 755688)),
        ),
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 28, 15, 12, 17, 754691)),
        ),
        migrations.CreateModel(
            name='CustomerAuthentication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_no', models.IntegerField()),
                ('dynamic_qr', models.CharField(max_length=1000)),
                ('restaurant', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='setup.venue')),
            ],
        ),
    ]
