# Generated by Django 3.1 on 2020-12-28 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0018_auto_20201228_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerauthentication',
            old_name='dynamic_qr',
            new_name='hashcode',
        ),
        migrations.AlterField(
            model_name='archiveorder',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 28, 16, 22, 1, 844446)),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 28, 16, 22, 1, 844446)),
        ),
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 28, 16, 22, 1, 843449)),
        ),
    ]
