# Generated by Django 3.1 on 2021-01-19 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0020_auto_20210117_0028'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifyOrder',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=5000)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2021, 1, 19, 21, 54, 4, 171078))),
            ],
        ),
        migrations.AlterField(
            model_name='archiveorder',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 19, 21, 54, 4, 172075)),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 19, 21, 54, 4, 172075)),
        ),
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 19, 21, 54, 4, 171078)),
        ),
    ]
