# Generated by Django 3.1 on 2021-01-19 18:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0009_auto_20201209_1510'),
        ('customerapp', '0021_auto_20210119_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifyorder',
            name='restaurant',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='setup.venue'),
        ),
        migrations.AddField(
            model_name='verifyorder',
            name='totalamount',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='archiveorder',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 19, 23, 43, 38, 28389)),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 19, 23, 43, 38, 29386)),
        ),
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 19, 23, 43, 38, 27391)),
        ),
        migrations.AlterField(
            model_name='verifyorder',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 19, 23, 43, 38, 28389)),
        ),
    ]
