# Generated by Django 3.1 on 2021-01-20 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0025_auto_20210120_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifyorder',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='archiveorder',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 20, 21, 29, 56, 353869)),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 20, 21, 29, 56, 353869)),
        ),
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 20, 21, 29, 56, 351875)),
        ),
        migrations.AlterField(
            model_name='verifyorder',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 20, 21, 29, 56, 352874)),
        ),
    ]
