# Generated by Django 3.1.6 on 2021-03-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calldetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalcode', models.CharField(default='', max_length=100)),
                ('videoname', models.CharField(max_length=20)),
                ('description', models.TextField(null=True)),
                ('videolink', models.CharField(max_length=100)),
                ('thumbnaillink', models.CharField(max_length=100)),
            ],
        ),
    ]
