# Generated by Django 3.1 on 2020-09-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='modalcode',
            field=models.CharField(default='', max_length=100),
        ),
    ]
