# Generated by Django 3.1 on 2020-12-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0002_tutorial_modalcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calldetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
            ],
        ),
    ]
