# Generated by Django 3.1 on 2020-12-12 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0003_calldetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Calldetails',
            new_name='Calldetail',
        ),
    ]
