# Generated by Django 3.1.6 on 2021-04-27 15:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=5000)),
                ('status', models.IntegerField()),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2021, 4, 27, 21, 16, 5, 914442))),
                ('restaurant', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='setup.venue')),
            ],
        ),
    ]
