# Generated by Django 3.1.6 on 2021-07-10 16:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=5000)),
                ('name', models.CharField(default='name', max_length=100)),
                ('phone', models.CharField(default='phone', max_length=15)),
                ('address', models.CharField(default='address', max_length=5000)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2021, 7, 10, 21, 35, 9, 218625))),
                ('status', models.IntegerField(default=0)),
                ('restaurant', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='setup.venue')),
            ],
        ),
        migrations.CreateModel(
            name='ArchiveDeliveryOrder',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=5000)),
                ('name', models.CharField(default='name', max_length=100)),
                ('phone', models.CharField(default='phone', max_length=15)),
                ('address', models.CharField(default='address', max_length=5000)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2021, 7, 10, 21, 35, 9, 218625))),
                ('status', models.IntegerField(default=0)),
                ('restaurant', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='setup.venue')),
            ],
        ),
    ]
