# Generated by Django 3.1.6 on 2021-04-27 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverycustomerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='address',
            field=models.CharField(default='address', max_length=5000),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='name',
            field=models.CharField(default='name', max_length=100),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='phone',
            field=models.CharField(default='phone', max_length=15),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 27, 22, 5, 10, 430334)),
        ),
    ]
