# Generated by Django 3.1.6 on 2021-07-10 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverycustomerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedeliveryorder',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 10, 21, 36, 42, 209380)),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 10, 21, 36, 42, 209380)),
        ),
    ]
