# Generated by Django 3.1.6 on 2021-04-30 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverycustomerapp', '0002_auto_20210427_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryorder',
            name='status',
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 30, 20, 19, 48, 537661)),
        ),
    ]
