# Generated by Django 3.1.6 on 2021-06-14 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverycustomerapp', '0002_auto_20210614_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedeliveryorder',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 14, 16, 36, 25, 493736)),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 14, 16, 36, 25, 493736)),
        ),
    ]
