# Generated by Django 3.1.6 on 2021-07-08 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverycustomerapp', '0002_auto_20210708_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedeliveryorder',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 8, 22, 59, 37, 41345)),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 8, 22, 59, 37, 40353)),
        ),
    ]
