# Generated by Django 3.1.6 on 2021-05-02 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverycustomerapp', '0003_auto_20210430_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 2, 21, 5, 7, 396860)),
        ),
    ]
