# Generated by Django 3.1.6 on 2021-05-04 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverycustomerapp', '0004_auto_20210502_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 4, 20, 35, 4, 636023)),
        ),
    ]
