# Generated by Django 3.1.6 on 2021-07-08 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverycustomerapp', '0014_auto_20210708_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedeliveryorder',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 8, 15, 29, 19, 450921)),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 8, 15, 29, 19, 450921)),
        ),
    ]
