# Generated by Django 3.1 on 2020-08-26 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('venueid', models.AutoField(primary_key=True, serialize=False)),
                ('venuename', models.CharField(max_length=50)),
                ('notables', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employeeid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('ph', models.CharField(max_length=12)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.venue')),
            ],
        ),
    ]
