# Generated by Django 3.1.6 on 2021-06-14 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('venueid', models.AutoField(primary_key=True, serialize=False)),
                ('venuename', models.CharField(max_length=50)),
                ('notables', models.IntegerField(default=0)),
                ('paymentphone', models.CharField(default='0', max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('venuename', models.CharField(default='venuename', max_length=100)),
                ('product_name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=300, null=True)),
                ('price', models.IntegerField(default=0)),
                ('showtype', models.BooleanField(default=1)),
                ('availability', models.CharField(choices=[('ava', 'Available'), ('not', 'Not Available')], default='ava', max_length=3)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.venue')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employeeid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('ph', models.CharField(max_length=12)),
                ('role', models.CharField(default=True, max_length=20)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.venue')),
            ],
        ),
    ]
