# Generated by Django 3.1.6 on 2021-05-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='venuename',
            field=models.CharField(default='venuename', max_length=100),
        ),
    ]
