# Generated by Django 3.1.6 on 2021-07-08 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='category_list_sorted',
        ),
    ]
