# Generated by Django 3.1.6 on 2021-06-14 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='paymentphone',
        ),
    ]
