# Generated by Django 3.1.6 on 2021-07-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0002_remove_menu_serialno'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='serialno',
            field=models.IntegerField(default=0),
        ),
    ]
