# Generated by Django 3.1.6 on 2021-06-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0002_menu_venuename'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='paymentphone',
            field=models.IntegerField(default=0),
        ),
    ]
