# Generated by Django 3.1.6 on 2021-07-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0002_remove_venue_category_list_sorted'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='category_list_sorted',
            field=models.CharField(default='0', max_length=500),
        ),
    ]
