# Generated by Django 3.1.6 on 2021-06-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0002_remove_venue_paymentphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='paymentphone',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
