# Generated by Django 3.1 on 2020-09-01 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0004_venuetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=300, null=True)),
                ('price', models.IntegerField(default=0)),
                ('image', models.ImageField(null=True, upload_to='rajputra/images')),
                ('availability', models.CharField(choices=[('ava', 'Available'), ('not', 'Not Available')], default='', max_length=3)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.venue')),
            ],
        ),
    ]
