# Generated by Django 3.1 on 2020-10-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0006_auto_20200906_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='availability',
            field=models.CharField(choices=[('ava', 'Available'), ('not', 'Not Available')], default='ava', max_length=3),
        ),
    ]
