# Generated by Django 3.1.6 on 2021-06-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0006_venue_paymentphoneno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='paymentphone',
        ),
        migrations.AddField(
            model_name='menu',
            name='pictype',
            field=models.BooleanField(default=1),
        ),
    ]
