# Generated by Django 3.1 on 2020-12-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0007_auto_20201012_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='cgst',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='venue',
            name='sgst',
            field=models.IntegerField(default=0),
        ),
    ]
