# Generated by Django 3.1.6 on 2021-06-23 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0007_auto_20210623_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='pictype',
        ),
    ]
