# Generated by Django 3.1.6 on 2021-06-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0008_remove_menu_pictype'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='pictype',
            field=models.BooleanField(default=1),
        ),
    ]
