# Generated by Django 3.1 on 2020-12-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0008_auto_20201209_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='cgst',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='venue',
            name='sgst',
            field=models.IntegerField(default=2),
        ),
    ]
