# Generated by Django 3.1.6 on 2021-07-08 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0009_menu_pictype'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='customisable',
            field=models.BooleanField(default=0),
        ),
        migrations.CreateModel(
            name='CustomItem',
            fields=[
                ('customitem_id', models.AutoField(primary_key=True, serialize=False)),
                ('customitemname', models.CharField(default='customitemname', max_length=50)),
                ('customitemprice', models.IntegerField(default=0)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.menu')),
            ],
        ),
    ]
