# Generated by Django 3.1 on 2021-01-27 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0009_auto_20201209_1510'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VenueTable',
        ),
    ]
