# Generated by Django 3.1 on 2021-02-09 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0011_menu_showtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='cgst',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='sgst',
        ),
    ]
