# Generated by Django 3.1 on 2021-02-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0012_auto_20210209_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
