# Generated by Django 3.1 on 2021-02-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cgst', models.IntegerField(default=2.5)),
                ('sgst', models.IntegerField(default=2.5)),
            ],
        ),
    ]
