# Generated by Django 3.1 on 2021-02-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gst',
            name='cgst',
            field=models.FloatField(default=2.5),
        ),
        migrations.AlterField(
            model_name='gst',
            name='sgst',
            field=models.FloatField(default=2.5),
        ),
    ]
