# Generated by Django 3.1 on 2021-02-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210209_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gst',
            name='cgst',
            field=models.DecimalField(decimal_places=4, max_digits=4),
        ),
        migrations.AlterField(
            model_name='gst',
            name='sgst',
            field=models.DecimalField(decimal_places=4, max_digits=4),
        ),
    ]
