# Generated by Django 3.1 on 2021-02-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210209_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gst',
            name='cgst',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='gst',
            name='sgst',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
